In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [34]:
# Install tpot on the server
!pip install tpot

In [35]:
from tpot import TPOTRegressor

In [36]:
#food_price_test = pd.read_csv("C:/Users/REVANTH/Desktop/ISB AMPBA/Term -6/FP2/corn_price_test.csv")
food_price_test =  "C:/Users/cmpl2/Documents/corn_price_test.csv"
print(food_price_test)

C:/Users/cmpl2/Documents/corn_price_test.csv


In [37]:
#cleaned_food_price = pd.read_csv("C:/Users/REVANTH/Desktop/ISB AMPBA/Term -6/FP2/Dataset Cleaned files/cleaned_corn_price.csv")
cleaned_food_price = "C:/Users/cmpl2/Documents/cleaned_corn_price.csv"
print(cleaned_food_price)

C:/Users/cmpl2/Documents/cleaned_corn_price.csv


In [38]:
# open files
test = np.genfromtxt(food_price_test,delimiter=',',skip_header=1)
train = np.genfromtxt(cleaned_food_price,delimiter=',',skip_header=1)
print(train)

[[3.360e+02 2.016e+03 3.000e+00 3.100e+01]
 [3.520e+02 2.016e+03 3.000e+00 3.000e+01]
 [3.560e+02 2.016e+03 3.000e+00 2.900e+01]
 [3.540e+02 2.016e+03 3.000e+00 2.800e+01]
 [3.530e+02 2.016e+03 3.000e+00 2.400e+01]
 [3.520e+02 2.016e+03 3.000e+00 2.300e+01]
 [3.520e+02 2.016e+03 3.000e+00 2.200e+01]
 [3.520e+02 2.016e+03 3.000e+00 2.100e+01]
 [3.490e+02 2.016e+03 3.000e+00 1.800e+01]
 [3.500e+02 2.016e+03 3.000e+00 1.700e+01]
 [3.500e+02 2.016e+03 3.000e+00 1.600e+01]
 [3.500e+02 2.016e+03 3.000e+00 1.500e+01]
 [3.500e+02 2.016e+03 3.000e+00 1.400e+01]
 [3.460e+02 2.016e+03 3.000e+00 1.100e+01]
 [3.440e+02 2.016e+03 3.000e+00 1.000e+01]
 [3.420e+02 2.016e+03 3.000e+00 9.000e+00]
 [3.420e+02 2.016e+03 3.000e+00 8.000e+00]
 [3.410e+02 2.016e+03 3.000e+00 7.000e+00]
 [3.410e+02 2.016e+03 3.000e+00 4.000e+00]
 [3.410e+02 2.016e+03 3.000e+00 3.000e+00]
 [3.410e+02 2.016e+03 3.000e+00 2.000e+00]
 [3.430e+02 2.016e+03 3.000e+00 1.000e+00]
 [3.440e+02 2.016e+03 2.000e+00 2.900e+01]
 [3.450e+02

In [39]:
#Create a copy of training without class
train_new = np.delete(train,0,1)

In [40]:
#Get list of class variables
train_class = train[:,0]

In [41]:
#Split the data inti training and testing sets
x_train,x_test, y_train ,y_test = train_test_split(train_new, train_class, train_size=0.75, test_size=0.25)

In [42]:
#Instantiate tpot instance
tpot = TPOTRegressor(verbosity=3, generations=10,scoring='balanced_accuracy', population_size=25)

In [43]:
#call fit function
tpot.fit(x_train, y_train)

30 operators have been imported by TPOT.


Optimization Progress:   0%|          | 0/275 [00:00<?, ?pipeline/s]

_pre_test decorator: _random_mutation_operator: num_test=0 cosine was provided as affinity. Ward can only work with euclidean distances..

Generation 1 - Current Pareto front scores:

-1	0.5290729918229918	AdaBoostRegressor(input_matrix, AdaBoostRegressor__learning_rate=1.0, AdaBoostRegressor__loss=square, AdaBoostRegressor__n_estimators=100)

-2	0.5306487493987494	AdaBoostRegressor(RobustScaler(input_matrix), AdaBoostRegressor__learning_rate=1.0, AdaBoostRegressor__loss=square, AdaBoostRegressor__n_estimators=100)
_pre_test decorator: _random_mutation_operator: num_test=0 Found array with 0 feature(s) (shape=(27, 0)) while a minimum of 1 is required..
_pre_test decorator: _random_mutation_operator: num_test=0 array must not contain infs or NaNs.

Generation 2 - Current Pareto front scores:

-1	0.5290729918229918	AdaBoostRegressor(input_matrix, AdaBoostRegressor__learning_rate=1.0, AdaBoostRegressor__loss=square, AdaBoostRegressor__n_estimators=100)

-2	0.5306487493987494	AdaBoostRegre

_pre_test decorator: _random_mutation_operator: num_test=0 Unsupported set of arguments: The combination of penalty='l2' and loss='epsilon_insensitive' are not supported when dual=False, Parameters: penalty='l2', loss='epsilon_insensitive', dual=False.
_pre_test decorator: _random_mutation_operator: num_test=0 Cosine affinity cannot be used when X contains zero vectors.

Generation 10 - Current Pareto front scores:

-1	0.5290729918229918	AdaBoostRegressor(input_matrix, AdaBoostRegressor__learning_rate=1.0, AdaBoostRegressor__loss=square, AdaBoostRegressor__n_estimators=100)

-2	0.5534920634920636	AdaBoostRegressor(SelectFromModel(input_matrix, SelectFromModel__ExtraTreesRegressor__max_features=0.1, SelectFromModel__ExtraTreesRegressor__n_estimators=100, SelectFromModel__threshold=0.0), AdaBoostRegressor__learning_rate=1.0, AdaBoostRegressor__loss=square, AdaBoostRegressor__n_estimators=100)

-3	0.5690981240981241	AdaBoostRegressor(AdaBoostRegressor(RobustScaler(input_matrix), AdaBoostR

TPOTRegressor(generations=10, population_size=25, scoring='balanced_accuracy',
              verbosity=3)

In [44]:
#call the score function on cv data
print('TPOT score: {}'.format(tpot.score(x_test, y_test)))

TPOT score: 0.5025252525252526


In [45]:
#Predict prices for each month for next 5 years
submission = tpot.predict(test)

In [46]:
#create dataframe of results for each month/years
final = pd.DataFrame ({'year': test[:,0],'month':test[:,1],'Pred':submission})

In [47]:
from sklearn.metrics import mean_squared_error
print('MSE:')
print(mean_squared_error(y_test, tpot.predict(x_test)))

MSE:
19.65659657802515


In [48]:
print('RMSE:')
print(np.sqrt(mean_squared_error(y_test, tpot.predict(x_test))))

RMSE:
4.433576048521684


In [50]:
#export pipeline
export_filename = 'Food Price Prediction Pipeline.py'
tpot.export(export_filename)

In [51]:
#export predicted values
final_filename = 'C:/Users/cmpl2/Documents/corn_price_pred.csv'
final.to_csv(final_filename, index=False)